### ISSUE TITLE
Requesting a delete asset and use cases feature

### ISSUE THREAD

**Issue by koleshjr** [highwind-ai/zindi-melio-mlops-machine-translation-challenge#3]
**Is your feature request related to a problem? Please describe.**
One can push an asset that has a bug that causes deployment to fail. These assets remain in our profile and this is annoying
**Describe the solution you'd like**
A feature to delete assets and use cases we do not need

**Describe alternatives you've considered**
Creating new assets and use cases

**Comment by philipstaffordwood** [comment]
Hi @koleshjr 

The functionality you want is called **Archive**.

On the **View Asset** page you can click the **Archive** button.
Afterwards it will no longer show up on your **View Assets** page.

Detailed steps:

If you start on the **My Assets** page,
you can navigate to the **View Asset** page of the Asset you want to remove by clicking on the the **View** button.
(1) in the image below:
![image](https://github.com/user-attachments/assets/7a9a9afc-12f3-4773-bdd9-de41dbc5b289)

This should take you to the **View Asset** page.
Here you can click the **Archive** button.
(2) in the image below:

![image](https://github.com/user-attachments/assets/bf041f58-2402-4f75-bc0b-1942c872094c)

After this the offending Asset should no longer appear in your **My Assets** list.
