### ISSUE TITLE
Error in Image Size Calculation on Zindi leaderboard?

### ISSUE THREAD

**Issue by JuliusFx131** [highwind-ai/zindi-melio-mlops-machine-translation-challenge#5]
A Docker image with a size of 1.85GB  (https://frontend.zindi.highwind.cloud/assets/73218dcc-5435-4b40-bebe-cd00e0254c3d) scores lower on size metric on the Zindi Leaderboard (0.822) compared to a larger Docker image of 2.1GB (https://frontend.zindi.highwind.cloud/assets/d5476614-3855-47ae-ae27-2eb203cda9b9), which has a score of 0.788.

According to the competition guidelines, a smaller image size is preferable.

Why does this discrepancy occur?

<img width="960" alt="1" src="https://github.com/user-attachments/assets/a5ab847b-a26f-4350-84d2-14fe03390670">
<img width="849" alt="2" src="https://github.com/user-attachments/assets/9c63a254-7649-4936-87c0-1ec79c71dec3">
<img width="896" alt="3" src="https://github.com/user-attachments/assets/5a6d7558-affb-4595-8bbf-5f3eccf36765">

**Comment by JuliusFx131** [comment]
<img width="832" alt="4" src="https://github.com/user-attachments/assets/9aae6fe8-53bf-4519-8fdd-f3884ca21832">

**Comment by ruankie** [comment]
Hi @JuliusFx131 
Thanks for the question!

Indeed, lower image sizes are what we want for the competition. Smaller images should therefore score better (higher).

If I understand correctly, you are concerned with these two images and the "direction" of the score we apply to them:


ID | Image size (GB) | Rubric score
-- | -- | --
A | 1.85 | 0.8224
B | 2.21 | 0.7883

In the table above, the smaller image (A) has a higher rubric score than the bigger image (B) as expected. Higher scores in the rubric contribute to a higher overall score.

I hope that helps. If you have any more questions, please don't hesitate to ask 😄

**Comment by JuliusFx131** [comment]
Makes lot of sense now. I am good. Let me continue optimizing for this tough challenge
